T = readtable("/Users/loganknudsen/Documents/GitHub/StormSurge/Experiment_Data/final_error/ensemble_cases.csv");
disp(T)
t0 = table2array(T(:,"Var1"));
figure(1)
plot(t0,table2array(T(:,"Case_H")),"b","LineWidth",3)
xlabel("Ensemble Size",'Interpreter',"latex")
ylabel("Mean Square Difference",'Interpreter',"latex")
title("Ensemble Size vs. Mean Square Difference of H",'Interpreter',"latex")
fontsize(20,"points")
saveas(gcf, "/Users/loganknudsen/Documents/GitHub/StormSurge/Manuscript_Plots/Mean_Square_Difference_of_H.png")
figure(2)
plot(t0,table2array(T(:,"Case_L")),"b","LineWidth",3)
xlabel("Ensemble Size",'Interpreter',"latex")
ylabel("Mean Square Difference",'Interpreter',"latex")
title("Ensemble Size vs. Mean Square Difference of L",'Interpreter',"latex")
fontsize(20,"points")
saveas(gcf, "/Users/loganknudsen/Documents/GitHub/StormSurge/Manuscript_Plots/Mean_Square_Difference_of_L.png")
